root: true
env:
  node: true
extends: ["eslint:recommended"]
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  brace-style: 2
  comma-dangle: [1, "always-multiline"]
  curly: 2
  dot-notation: 1
  eqeqeq: [2, "smart"]
  no-console: 2
  no-debugger: 2
  no-extra-bind: 2
  no-implicit-coercion: 2
  no-trailing-spaces: 2
  no-unexpected-multiline: 2
  quotes: [1, "single", "avoid-escape"]
  keyword-spacing: 2
  spaced-comment: 2
  no-unused-vars: 
    - 2
    - varsIgnorePattern: "^_"
globals:
  Promise: true
  Map: true
  Set: true
  __DEV__: true
